# Generated by Django 3.2 on 2023-01-11 09:51

import django.core.validators
import django.db.models.deletion
import reviews.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="title",
            name="rating",
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=256, verbose_name="Category name"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                unique=True, verbose_name="Category slugname"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                help_text="Автор отзыва.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Comments author",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="reviews",
            field=models.ForeignKey(
                help_text="Комментарии к отзывам.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="reviews.review",
                verbose_name="Review comments",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(verbose_name="Comment text"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Genre name"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Genre slugname"),
        ),
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                help_text="Автор отзыва.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Review author",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                verbose_name="Publication date",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="score",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Title score",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(verbose_name="Review text"),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.ForeignKey(
                help_text="Отзывы на произведения.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="reviews.title",
                verbose_name="Title review",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="titles",
                to="reviews.category",
                verbose_name="Title category",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="description",
            field=models.TextField(verbose_name="Title description"),
        ),
        migrations.AlterField(
            model_name="title",
            name="genre",
            field=models.ManyToManyField(
                related_name="titles",
                through="reviews.TitleGenre",
                to="reviews.Genre",
                verbose_name="Title genres",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Ttitle name"),
        ),
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    reviews.models.validate_year,
                ],
                verbose_name="Title year",
            ),
        ),
        migrations.AlterField(
            model_name="titlegenre",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reviews.genre",
                verbose_name="Title genre",
            ),
        ),
        migrations.AlterField(
            model_name="titlegenre",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reviews.title",
                verbose_name="Title",
            ),
        ),
    ]
