# Generated by Django 3.2 on 2023-01-12 06:30

import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_auto_20230111_1251"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.PositiveSmallIntegerField(
                validators=[reviews.validators.validate_year],
                verbose_name="Title year",
            ),
        ),
    ]
